# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_lineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='category',
            field=models.CharField(default='food', max_length=100),
            preserve_default=False,
        ),
    ]
