# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180409_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category'),
        ),
    ]
