# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-13 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180412_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='titles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='recent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
